services:
  accounts:
    image: "akhilfrancis7/accounts:s6"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - akhilfrancis7
  loans:
    image: "akhilfrancis7/loans:s6"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - akhilfrancis7
  cards:
    image: "akhilfrancis7/cards:s6"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - akhilfrancis7
networks:
  akhilfrancis7:
    driver: "bridge"