build:
  version: "3.0"

cards:
  message: "Welcome to akhilfrancis cards related local APIs "
  contactDetails:
    name: "Akhil Francis - Developer"
    email: "akhilfrancis"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
