build:
  version: "3.0"

loans:
  message: "Welcome to akhilfrancis loans related local APIs "
  contactDetails:
    name: "Akhil Francis - Developer"
    email: "akhilfrancis"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345