build:
  version: "1.0"

loans:
  message: "Welcome to akhilfrancis loans related Prod APIs "
  contactDetails:
    name: "Akhil Francis - Prod"
    email: "akhilfrancis"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345