spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/AkhilFrancis/Bank-Microservices-App-Config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "A3D4F1C2B998E0F17A4C99DDEE5213BF"

server:
  port: 8071